
package jp.sales.oio.oiobama.web.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CoreException", targetNamespace = "http://service.web.oiobama.oio.sales.jp/")
public class CoreException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CoreException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CoreException_Exception(String message, CoreException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CoreException_Exception(String message, CoreException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: jp.sales.oio.oiobama.web.service.CoreException
     */
    public CoreException getFaultInfo() {
        return faultInfo;
    }

}
