
package jp.sales.oio.oiobama.web.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OIOServer", targetNamespace = "http://service.web.oiobama.oio.sales.jp/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OIOServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws CoreException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.AuthenticateResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/authenticateRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/authenticateResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/authenticate/Fault/CoreException")
    })
    public String authenticate()
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws CoreException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createCustomer", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.CreateCustomer")
    @ResponseWrapper(localName = "createCustomerResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.CreateCustomerResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/createCustomerRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/createCustomerResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/createCustomer/Fault/CoreException")
    })
    public void createCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        MContractBase arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws CoreException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateCustomer", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.UpdateCustomer")
    @ResponseWrapper(localName = "updateCustomerResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.UpdateCustomerResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/updateCustomerRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/updateCustomerResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/updateCustomer/Fault/CoreException")
    })
    public void updateCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        MContractBase arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<jp.sales.oio.oiobama.web.service.MContractBase>
     * @throws CoreException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "referCustomers", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferCustomers")
    @ResponseWrapper(localName = "referCustomersResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferCustomersResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/referCustomersRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/referCustomersResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/referCustomers/Fault/CoreException")
    })
    public List<MContractBase> referCustomers()
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns jp.sales.oio.oiobama.web.service.MContractBase
     * @throws CoreException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "referCustomer", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferCustomer")
    @ResponseWrapper(localName = "referCustomerResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferCustomerResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/referCustomerRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/referCustomerResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/referCustomer/Fault/CoreException")
    })
    public MContractBase referCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws CoreException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createContractDetail", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.CreateContractDetail")
    @ResponseWrapper(localName = "createContractDetailResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.CreateContractDetailResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/createContractDetailRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/createContractDetailResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/createContractDetail/Fault/CoreException")
    })
    public void createContractDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        MContractDetail arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws CoreException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateContractDetail", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.UpdateContractDetail")
    @ResponseWrapper(localName = "updateContractDetailResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.UpdateContractDetailResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/updateContractDetailRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/updateContractDetailResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/updateContractDetail/Fault/CoreException")
    })
    public void updateContractDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        MContractDetail arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<jp.sales.oio.oiobama.web.service.MContractDetail>
     * @throws CoreException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "referContractDetailsAll", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferContractDetailsAll")
    @ResponseWrapper(localName = "referContractDetailsAllResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferContractDetailsAllResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractDetailsAllRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractDetailsAllResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractDetailsAll/Fault/CoreException")
    })
    public List<MContractDetail> referContractDetailsAll()
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<jp.sales.oio.oiobama.web.service.MContractDetail>
     * @throws CoreException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "referContractDetails", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferContractDetails")
    @ResponseWrapper(localName = "referContractDetailsResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferContractDetailsResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractDetailsRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractDetailsResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractDetails/Fault/CoreException")
    })
    public List<MContractDetail> referContractDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns jp.sales.oio.oiobama.web.service.MContractDetail
     * @throws CoreException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "referContractDetail", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferContractDetail")
    @ResponseWrapper(localName = "referContractDetailResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferContractDetailResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractDetailRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractDetailResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractDetail/Fault/CoreException")
    })
    public MContractDetail referContractDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1)
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws CoreException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createPlan", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.CreatePlan")
    @ResponseWrapper(localName = "createPlanResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.CreatePlanResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/createPlanRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/createPlanResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/createPlan/Fault/CoreException")
    })
    public void createPlan(
        @WebParam(name = "arg0", targetNamespace = "")
        MPlan arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws CoreException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updatePlan", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.UpdatePlan")
    @ResponseWrapper(localName = "updatePlanResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.UpdatePlanResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/updatePlanRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/updatePlanResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/updatePlan/Fault/CoreException")
    })
    public void updatePlan(
        @WebParam(name = "arg0", targetNamespace = "")
        MPlan arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws CoreException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deletePlan", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.DeletePlan")
    @ResponseWrapper(localName = "deletePlanResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.DeletePlanResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/deletePlanRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/deletePlanResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/deletePlan/Fault/CoreException")
    })
    public void deletePlan(
        @WebParam(name = "arg0", targetNamespace = "")
        MPlan arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<jp.sales.oio.oiobama.web.service.MPlan>
     * @throws CoreException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "referPlansAll", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferPlansAll")
    @ResponseWrapper(localName = "referPlansAllResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferPlansAllResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/referPlansAllRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/referPlansAllResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/referPlansAll/Fault/CoreException")
    })
    public List<MPlan> referPlansAll()
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<jp.sales.oio.oiobama.web.service.MPlan>
     * @throws CoreException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "referPlans", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferPlans")
    @ResponseWrapper(localName = "referPlansResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferPlansResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/referPlansRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/referPlansResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/referPlans/Fault/CoreException")
    })
    public List<MPlan> referPlans(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws CoreException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createContractTemp", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.CreateContractTemp")
    @ResponseWrapper(localName = "createContractTempResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.CreateContractTempResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/createContractTempRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/createContractTempResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/createContractTemp/Fault/CoreException")
    })
    public void createContractTemp(
        @WebParam(name = "arg0", targetNamespace = "")
        MContractTemp arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws CoreException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateContractTemp", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.UpdateContractTemp")
    @ResponseWrapper(localName = "updateContractTempResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.UpdateContractTempResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/updateContractTempRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/updateContractTempResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/updateContractTemp/Fault/CoreException")
    })
    public void updateContractTemp(
        @WebParam(name = "arg0", targetNamespace = "")
        MContractTemp arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<jp.sales.oio.oiobama.web.service.MContractTemp>
     * @throws CoreException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "referContractTempsAll", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferContractTempsAll")
    @ResponseWrapper(localName = "referContractTempsAllResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferContractTempsAllResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractTempsAllRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractTempsAllResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractTempsAll/Fault/CoreException")
    })
    public List<MContractTemp> referContractTempsAll()
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<jp.sales.oio.oiobama.web.service.MContractTemp>
     * @throws CoreException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "referContractTemps", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferContractTemps")
    @ResponseWrapper(localName = "referContractTempsResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferContractTempsResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractTempsRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractTempsResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/referContractTemps/Fault/CoreException")
    })
    public List<MContractTemp> referContractTemps(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws CoreException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<jp.sales.oio.oiobama.web.service.TPprice>
     * @throws CoreException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "referHistorysAll", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferHistorysAll")
    @ResponseWrapper(localName = "referHistorysAllResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferHistorysAllResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/referHistorysAllRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/referHistorysAllResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/referHistorysAll/Fault/CoreException")
    })
    public List<TPprice> referHistorysAll()
        throws CoreException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<jp.sales.oio.oiobama.web.service.TPprice>
     * @throws CoreException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "referHistorys", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferHistorys")
    @ResponseWrapper(localName = "referHistorysResponse", targetNamespace = "http://service.web.oiobama.oio.sales.jp/", className = "jp.sales.oio.oiobama.web.service.ReferHistorysResponse")
    @Action(input = "http://service.web.oiobama.oio.sales.jp/OIOServer/referHistorysRequest", output = "http://service.web.oiobama.oio.sales.jp/OIOServer/referHistorysResponse", fault = {
        @FaultAction(className = CoreException_Exception.class, value = "http://service.web.oiobama.oio.sales.jp/OIOServer/referHistorys/Fault/CoreException")
    })
    public List<TPprice> referHistorys(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws CoreException_Exception
    ;

}
